// Catalogo de CWE para el selector del editor de hallazgos.
//
// Orden y seleccion: ranking de HackerOne por cantidad de reportes (los mas
// usados primero). Evita tener que buscar el numero a mano; el editor igual
// permite escribir un CWE que no este aca.
//
// Los nombres son los oficiales del MITRE/HackerOne. Como esos nombres no
// incluyen las siglas habituales (XSS, IDOR, XXE...), `aliases` agrega esos
// terminos para que la busqueda por sigla funcione.

export interface CweEntry {
  /** Identificador con prefijo, por ejemplo "CWE-89". */
  id: string;
  /** Nombre oficial del CWE. */
  name: string;
  /** Siglas o terminos alternativos para la busqueda (no se muestran). */
  aliases?: string[];
}

export const COMMON_CWES: CweEntry[] = [
  {
    id: "CWE-79",
    name: "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
    aliases: ["XSS"],
  },
  { id: "CWE-200", name: "Exposure of Sensitive Information to an Unauthorized Actor" },
  { id: "CWE-284", name: "Improper Access Control" },
  { id: "CWE-639", name: "Authorization Bypass Through User-Controlled Key", aliases: ["IDOR"] },
  { id: "CWE-287", name: "Improper Authentication" },
  { id: "CWE-657", name: "Violation of Secure Design Principles" },
  { id: "CWE-601", name: "URL Redirection to Untrusted Site ('Open Redirect')" },
  { id: "CWE-352", name: "Cross-Site Request Forgery (CSRF)" },
  {
    id: "CWE-89",
    name: "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
    aliases: ["SQLi"],
  },
  {
    id: "CWE-444",
    name: "Inconsistent Interpretation of HTTP Requests ('HTTP Request/Response Smuggling')",
    aliases: ["Smuggling"],
  },
  { id: "CWE-94", name: "Improper Control of Generation of Code ('Code Injection')", aliases: ["RCE"] },
  { id: "CWE-918", name: "Server-Side Request Forgery (SSRF)", aliases: ["SSRF"] },
  { id: "CWE-285", name: "Improper Authorization" },
  { id: "CWE-20", name: "Improper Input Validation" },
  { id: "CWE-400", name: "Uncontrolled Resource Consumption", aliases: ["DoS"] },
  { id: "CWE-307", name: "Improper Restriction of Excessive Authentication Attempts" },
  { id: "CWE-922", name: "Insecure Storage of Sensitive Information" },
  { id: "CWE-215", name: "Insertion of Sensitive Information Into Debugging Code" },
  { id: "CWE-807", name: "Reliance on Untrusted Inputs in a Security Decision" },
  { id: "CWE-312", name: "Cleartext Storage of Sensitive Information" },
  { id: "CWE-22", name: "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')" },
  {
    id: "CWE-78",
    name: "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
    aliases: ["RCE"],
  },
  { id: "CWE-610", name: "Externally Controlled Reference to a Resource in Another Sphere" },
  { id: "CWE-77", name: "Improper Neutralization of Special Elements used in a Command ('Command Injection')" },
  {
    id: "CWE-80",
    name: "Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)",
    aliases: ["XSS"],
  },
  { id: "CWE-321", name: "Use of Hard-coded Cryptographic Key" },
  { id: "CWE-119", name: "Improper Restriction of Operations within the Bounds of a Memory Buffer" },
  { id: "CWE-99", name: "Improper Control of Resource Identifiers ('Resource Injection')" },
  { id: "CWE-209", name: "Generation of Error Message Containing Sensitive Information" },
  { id: "CWE-770", name: "Allocation of Resources Without Limits or Throttling" },
  { id: "CWE-798", name: "Use of Hard-coded Credentials" },
  { id: "CWE-288", name: "Authentication Bypass Using an Alternate Path or Channel" },
  { id: "CWE-613", name: "Insufficient Session Expiration" },
  { id: "CWE-319", name: "Cleartext Transmission of Sensitive Information" },
  { id: "CWE-548", name: "Exposure of Information Through Directory Listing" },
  { id: "CWE-311", name: "Missing Encryption of Sensitive Data" },
  { id: "CWE-863", name: "Incorrect Authorization" },
  { id: "CWE-522", name: "Insufficiently Protected Credentials" },
  { id: "CWE-611", name: "Improper Restriction of XML External Entity Reference", aliases: ["XXE"] },
  { id: "CWE-359", name: "Exposure of Private Personal Information to an Unauthorized Actor" },
  { id: "CWE-749", name: "Exposed Dangerous Method or Function" },
  { id: "CWE-862", name: "Missing Authorization" },
  { id: "CWE-129", name: "Improper Validation of Array Index" },
  { id: "CWE-125", name: "Out-of-bounds Read" },
  { id: "CWE-707", name: "Improper Neutralization" },
  { id: "CWE-306", name: "Missing Authentication for Critical Function" },
  { id: "CWE-93", name: "Improper Neutralization of CRLF Sequences ('CRLF Injection')", aliases: ["CRLF"] },
  { id: "CWE-434", name: "Unrestricted Upload of File with Dangerous Type" },
  { id: "CWE-602", name: "Client-Side Enforcement of Server-Side Security" },
  { id: "CWE-502", name: "Deserialization of Untrusted Data" },
  { id: "CWE-124", name: "Buffer Underwrite ('Buffer Underflow')" },
  { id: "CWE-126", name: "Buffer Over-read" },
  { id: "CWE-538", name: "Insertion of Sensitive Information into Externally-Accessible File or Directory" },
  { id: "CWE-120", name: "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')" },
  { id: "CWE-122", name: "Heap-based Buffer Overflow" },
  {
    id: "CWE-362",
    name: "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
    aliases: ["Race Condition"],
  },
  { id: "CWE-269", name: "Improper Privilege Management" },
  { id: "CWE-416", name: "Use After Free" },
  { id: "CWE-295", name: "Improper Certificate Validation" },
  { id: "CWE-324", name: "Use of a Key Past its Expiration Date" },
  { id: "CWE-367", name: "Time-of-check Time-of-use (TOCTOU) Race Condition", aliases: ["TOCTOU"] },
  { id: "CWE-425", name: "Direct Request ('Forced Browsing')" },
  { id: "CWE-384", name: "Session Fixation" },
  {
    id: "CWE-98",
    name: "Improper Control of Filename for Include/Require Statement in PHP Program ('PHP Remote File Inclusion')",
    aliases: ["RFI", "LFI"],
  },
  { id: "CWE-476", name: "NULL Pointer Dereference" },
  { id: "CWE-327", name: "Use of a Broken or Risky Cryptographic Algorithm" },
  { id: "CWE-640", name: "Weak Password Recovery Mechanism for Forgotten Password" },
  { id: "CWE-121", name: "Stack-based Buffer Overflow" },
  { id: "CWE-256", name: "Plaintext Storage of a Password" },
  { id: "CWE-300", name: "Channel Accessible by Non-Endpoint", aliases: ["MitM"] },
  { id: "CWE-280", name: "Improper Handling of Insufficient Permissions or Privileges" },
  { id: "CWE-36", name: "Absolute Path Traversal" },
  { id: "CWE-833", name: "Deadlock" },
  { id: "CWE-35", name: "Path Traversal: '.../...//'" },
  { id: "CWE-260", name: "Password in Configuration File" },
  { id: "CWE-201", name: "Insertion of Sensitive Information Into Sent Data" },
  { id: "CWE-190", name: "Integer Overflow or Wraparound" },
  { id: "CWE-1076", name: "Insufficient Adherence to Expected Conventions" },
  {
    id: "CWE-113",
    name: "Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Request/Response Splitting')",
    aliases: ["CRLF"],
  },
  { id: "CWE-326", name: "Inadequate Encryption Strength" },
  { id: "CWE-261", name: "Weak Encoding for Password" },
  { id: "CWE-203", name: "Observable Discrepancy" },
  { id: "CWE-644", name: "Improper Neutralization of HTTP Headers for Scripting Syntax" },
  { id: "CWE-259", name: "Use of Hard-coded Password" },
  { id: "CWE-656", name: "Reliance on Security Through Obscurity" },
  { id: "CWE-523", name: "Unprotected Transport of Credentials" },
  { id: "CWE-620", name: "Unverified Password Change" },
  { id: "CWE-843", name: "Access of Resource Using Incompatible Type ('Type Confusion')", aliases: ["Type Confusion"] },
  { id: "CWE-703", name: "Improper Check or Handling of Exceptional Conditions" },
  { id: "CWE-451", name: "User Interface (UI) Misrepresentation of Critical Information", aliases: ["Clickjacking"] },
  { id: "CWE-23", name: "Relative Path Traversal" },
  { id: "CWE-784", name: "Reliance on Cookies without Validation and Integrity Checking in a Security Decision" },
  { id: "CWE-91", name: "XML Injection (aka Blind XPath Injection)", aliases: ["XPath"] },
  { id: "CWE-257", name: "Storing Passwords in a Recoverable Format" },
  {
    id: "CWE-90",
    name: "Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')",
    aliases: ["LDAP"],
  },
  { id: "CWE-127", name: "Buffer Under-read" },
  { id: "CWE-642", name: "External Control of Critical State Data" },
  { id: "CWE-242", name: "Use of Inherently Dangerous Function" },
  { id: "CWE-191", name: "Integer Underflow (Wrap or Wraparound)" },
  {
    id: "CWE-75",
    name: "Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)",
  },
  { id: "CWE-134", name: "Use of Externally-Controlled Format String", aliases: ["Format String"] },
  { id: "CWE-296", name: "Improper Following of a Certificate's Chain of Trust" },
  { id: "CWE-123", name: "Write-what-where Condition" },
  { id: "CWE-489", name: "Active Debug Code" },
  { id: "CWE-328", name: "Use of Weak Hash" },
  { id: "CWE-325", name: "Missing Cryptographic Step" },
  { id: "CWE-338", name: "Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)", aliases: ["PRNG"] },
  { id: "CWE-776", name: "Improper Restriction of Recursive Entity References in DTDs ('XML Entity Expansion')" },
  { id: "CWE-208", name: "Observable Timing Discrepancy" },
  { id: "CWE-471", name: "Modification of Assumed-Immutable Data (MAID)" },
  { id: "CWE-506", name: "Embedded Malicious Code" },
  { id: "CWE-732", name: "Incorrect Permission Assignment for Critical Resource" },
  { id: "CWE-177", name: "Improper Handling of URL Encoding (Hex Encoding)" },
  { id: "CWE-150", name: "Improper Neutralization of Escape, Meta, or Control Sequences" },
  { id: "CWE-926", name: "Improper Export of Android Application Components" },
  { id: "CWE-170", name: "Improper Null Termination" },
  { id: "CWE-322", name: "Key Exchange without Entity Authentication" },
  { id: "CWE-193", name: "Off-by-one Error" },
  { id: "CWE-330", name: "Use of Insufficiently Random Values" },
  { id: "CWE-391", name: "Unchecked Error Condition" },
  { id: "CWE-131", name: "Incorrect Calculation of Buffer Size" },
  { id: "CWE-323", name: "Reusing a Nonce, Key Pair in Encryption" },
  { id: "CWE-377", name: "Insecure Temporary File" },
  { id: "CWE-184", name: "Incomplete List of Disallowed Inputs" },
  { id: "CWE-415", name: "Double Free" },
];
